# Generated by Django 4.2.7 on 2025-10-17 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='전화번호')),
                ('department', models.CharField(choices=[('development', '개발팀'), ('design', '디자인팀'), ('marketing', '마케팅팀'), ('sales', '영업팀'), ('hr', '인사팀'), ('finance', '재무팀'), ('management', '경영진')], max_length=20, verbose_name='부서')),
                ('position', models.CharField(choices=[('intern', '인턴'), ('junior', '주니어'), ('senior', '시니어'), ('lead', '리드'), ('manager', '매니저'), ('director', '디렉터'), ('ceo', 'CEO')], max_length=20, verbose_name='직급')),
                ('hire_date', models.DateField(verbose_name='입사일')),
                ('salary', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='급여')),
                ('is_active', models.BooleanField(default=True, verbose_name='재직 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '직원',
                'verbose_name_plural': '직원들',
                'ordering': ['-created_at'],
            },
        ),
    ]
