# Generated by Django 4.2.7 on 2025-10-27 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='증명사진'),
        ),
    ]
